"""initial migration

Revision ID: 3849b2658e6a
Revises: 
Create Date: 2025-05-09 17:55:48.755341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3849b2658e6a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('parent', sa.String(), nullable=False),
    sa.Column('taking_SAT', sa.Boolean(), nullable=False),
    sa.Column('taking_ACT', sa.Boolean(), nullable=False),
    sa.Column('target_SAT', sa.Integer(), nullable=True),
    sa.Column('target_ACT', sa.Integer(), nullable=True),
    sa.Column('actual_SAT', sa.Integer(), nullable=True),
    sa.Column('actual_ACT', sa.Integer(), nullable=True),
    sa.Column('active_student', sa.Boolean(), nullable=False),
    sa.Column('num_sessions', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('sessions_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('fk_students', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_students'], ['students_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tests_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('fk_students', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_students'], ['students_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tests_table')
    op.drop_table('sessions_table')
    op.drop_table('students_table')
    # ### end Alembic commands ###
