"""added test tables, inheritance, completion dates

Revision ID: bb0c417a79c7
Revises: 5d9176b68d79
Create Date: 2025-05-10 02:12:05.754797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb0c417a79c7'
down_revision: Union[str, None] = '5d9176b68d79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_completed', sa.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('session_notes', sa.String(), nullable=True))

    with op.batch_alter_table('tests_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('date_completed', sa.TIMESTAMP(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests_table', schema=None) as batch_op:
        batch_op.drop_column('date_completed')
        batch_op.drop_column('test_name')

    with op.batch_alter_table('sessions_table', schema=None) as batch_op:
        batch_op.drop_column('session_notes',)
        batch_op.drop_column('date_completed')

    # ### end Alembic commands ###
